#!/bin/sh -e

echo "building with docker. might take a while to pull..."
docker run --rm -v `pwd`:/go/src/github.com/sym3tri/hello -w /go/src/github.com/sym3tri/hello golang:1.4 ./build

echo "building docker image..."
docker build -q -t sym3tri/hello .

echo "done"
